<option value="">Choose One</option>
<option value="na">N&#47;A</option>
<option value="Senior in College">Senior &#40;College&#41;</option>
<option value="Junior in College">Junior &#40;College&#41;</option>
<option value="Sophmore in College">Sophmore &#40;College&#41;</option>
<option value="Freshman in College">Freshman &#40;College&#41;</option>
<option value="High School Senior">Senior &#40;HS&#41;</option>
<option value="High School Junior">Junior &#40;HS&#41;</option>
<option value="High School Sophmore">Sophmore &#40;HS&#41;</option>
<option value="High School Freshman">Freshman &#40;HS&#41;</option>
<option value="Eight Grade">8th</option>
<option value="Seventh Grade">7th</option>
<option value="Sixth Grade">6th</option>
<option value="Fifth Grade">5th</option>
<option value="Fourth Grade">4th</option>
<option value="Third Grade">3rd</option>
<option value="Second Grade">2nd</option>
<option value="First Grade">1st</option>